name: Build & Notarize

# on: 
#     push:
#         tags:
#             - 'v*.*.*'

on: "pull_request" # only active during testing

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest]

        steps:           
            # Checkout branch
            - uses: actions/checkout@v2

            # Node.js (for package scripts)
            -   uses: actions/setup-node@v1
                with:
                    node-version: "20.11"

            # Python
            -   uses: actions/setup-python@v4
                with:
                    python-version: "3.10"

            -   uses: snok/install-poetry@v1
                with:
                    version: "1.7.1"
                    virtualenvs-create: true
                    virtualenvs-in-project: false
                    virtualenvs-path: ~/my-custom-path
                    installer-parallel: true

            # Install all deps
            -   run: yarn install-deps

            -   name: "Build frontend with env vars"
                run: yarn build:frontend
                env: 
                    NODE_ENV: production
                    DEV_RPC: http://localhost:8545
                    FORK_URL: https://gnosis-pokt.nodies.app
                    
            #-   run: rm -rf /dist && GH_TOKEN=${{ secrets.github_token}} NODE_ENV=production npm exec --package=electron-builder -- electron-builder build --mac --arm64 --publish always
            
            - run: rm -rf /dist
            
            -   name: "Build, notarize, publish"
                env:
                    APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLEIDPASS }}
                    APPLE_ID: ${{ secrets.APPLEID }}
                    APPLETEAMID: ${{ secrets.APPLETEAMID }}
                    CSC_FOR_PULL_REQUEST: true
                    CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
                    CSC_LINK: ${{ secrets.CSC_LINK }}
                    DEV_RPC: http://localhost:8545
                    FORK_URL: https://gnosis-pokt.nodies.app
                    GH_TOKEN: ${{ secrets.github_token}}
                    NODE_ENV: production
                    PUBLISH_FOR_PULL_REQUEST: true #temporary during testing
                run: node build.js

            -   name: "Upload artifacts"
                uses: actions/upload-artifact@v4
                with:
                    path: dist/*.dmg