# TBA
name: Frontend Workflow

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.11"
      # Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.7.1"
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ~/my-custom-path
          installer-parallel: true
      # Install dependencies
      - name: Install dependencies
        run: yarn
      # Lint and test
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test